USE [master]
GO

/****** Object:  Database [Web_report]    Script Date: 01.02.2021 23:30:49 ******/
CREATE DATABASE [Web_report]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Web_report', FILENAME = N'D:\Other\SQLserverExpress\MSSQL14.SQLEXPRESS\MSSQL\DATA\Web_report.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Web_report_log', FILENAME = N'D:\Other\SQLserverExpress\MSSQL14.SQLEXPRESS\MSSQL\DATA\Web_report_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Web_report].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Web_report] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Web_report] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Web_report] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Web_report] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Web_report] SET ARITHABORT OFF 
GO

ALTER DATABASE [Web_report] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Web_report] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Web_report] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Web_report] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Web_report] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Web_report] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Web_report] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Web_report] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Web_report] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Web_report] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Web_report] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Web_report] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Web_report] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Web_report] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Web_report] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Web_report] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Web_report] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Web_report] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Web_report] SET  MULTI_USER 
GO

ALTER DATABASE [Web_report] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Web_report] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Web_report] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Web_report] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Web_report] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Web_report] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Web_report] SET  READ_WRITE 
GO


